### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by A-Programmer** [omerfarukz/autocomplete#2]
Hello.
How can I use this in asp.net core2?
I mea does it available as a nuget pakage?

**Comment by omerfarukz** [comment]
Hi,
Just published a new package named Autocomplete.Clients. 

Following code is for indexing:

    using(var header = new FileStream("header.bin", FileMode.CreateNew)) {
        using(var index = new FileStream("index.bin", FileMode.CreateNew)) {
            var builder = new IndexBuilder(header, index);

            builder.Add("foo");
            builder.Add("bar");
            builder.Build();
        }
    }

and following for search:


    // searcher declared just for example
    IndexSearcher searcher = new InMemoryIndexSearcher("header.bin", "index.bin");

    string keyword = "f"; // read given keyword
    var searchResult = searcher.Search(keyword, 10, true);

    if(searchResult.Items != null)
    {
        foreach(var item in searchResult.Items)
        {
            System.Console.WriteLine(item);
        }
    }
